name: pontibus
channels:
  - conda-forge
dependencies:
  - pip
  - gufe >=1.7
  - openff-toolkit >0.16.0
  - openff-interchange >=0.4.8
  - openff-nagl-base >=0.3.3
  # OpenFE stack deps
  - openfe >=1.7
  - duecredit<0.10
  - kartograf>=1.0.0
  - konnektor
  - lomap2>=3.0.0
  - numpy
  - networkx
  - rdkit
  - packaging
  - pip
  - pydantic >=2.0
  - pyyaml
  - coverage
  - cinnabar ~=0.5.0
  - click
  - typing-extensions
  - openmm >=8.0.0,!=8.1.0,<8.3.0
  - openmmtools >=0.25.0
  - openmmforcefields
  - openfe-analysis >=0.3.1
  - plugcli
  - tqdm
  # Testing deps
  - pytest
  - pytest-cov
  - pytest-xdist
